@startuml
Bootstrap -> Bootstrap :start()
 Bootstrap -> Catalina :start()
 Catalina -> LifecycleBase :start()
 LifecycleBase -> StandardServer :startInternal()
 StandardServer -> LifecycleBase :start()
 LifecycleBase -> StandardService :startInternal()
 StandardService -> LifecycleBase :start()
 LifecycleBase -> StandardEngine :startInternal()
 StandardEngine -> ContainerBase :startInternal()
 ContainerBase -> ContainerBase.StartChild :call()
 ContainerBase.StartChild -> ContainerBase.StartChild :call()
 ContainerBase.StartChild -> LifecycleBase :start()
 LifecycleBase -> StandardHost :startInternal()
 StandardHost -> ContainerBase :startInternal()
 ContainerBase -> LifecycleBase :setState()
 LifecycleBase -> LifecycleBase :setStateInternal()
 LifecycleBase -> LifecycleBase :fireLifecycleEvent()
 LifecycleBase -> LifecycleSupport :fireLifecycleEvent()
 LifecycleSupport -> HostConfig :lifecycleEvent()
 HostConfig -> HostConfig :start()
 HostConfig -> HostConfig :deployApps()
 HostConfig -> HostConfig :deployWARs()
 HostConfig -> HostConfig.DeployWar :run()
 HostConfig.DeployWar -> HostConfig :deployWAR()
@enduml