@startuml
  TaskThread.WrappingRunnable -> NioEndpoint.SocketProcessor :run()
   NioEndpoint.SocketProcessor -> NioEndpoint.SocketProcessor :doRun()
   NioEndpoint.SocketProcessor -> AbstractProtocol.AbstractConnectionHandler :process()
   AbstractProtocol.AbstractConnectionHandler -> AbstractHttp11Processor :process()
   AbstractHttp11Processor -> CoyoteAdapter :service()
   CoyoteAdapter -> StandardEngineValve :invoke()
   StandardEngineValve -> AbstractAccessLogValve :invoke()
   AbstractAccessLogValve -> ErrorReportValve :invoke()
   ErrorReportValve -> StandardHostValve :invoke()
   StandardHostValve -> StandardContextValve :invoke()
   StandardContextValve -> StandardWrapperValve :invoke()
   StandardWrapperValve -> ApplicationFilterChain :doFilter()
   ApplicationFilterChain -> ApplicationFilterChain :internalDoFilter()
   ApplicationFilterChain -> HttpServlet :service()
   HttpServlet -> JspServlet :service()
   JspServlet -> JspServlet :serviceJspFile()
   JspServlet -> JspServletWrapper :service()
   JspServletWrapper -> JspCompilationContext :compile()
@enduml