@startuml
TaskThread.WrappingRunnable -> NioEndpoint.SocketProcessor :run()
 NioEndpoint.SocketProcessor -> NioEndpoint.SocketProcessor :doRun()
 NioEndpoint.SocketProcessor -> AbstractProtocol.AbstractConnectionHandler :process()
 AbstractProtocol.AbstractConnectionHandler -> AbstractHttp11Processor :process()
 AbstractHttp11Processor -> CoyoteAdapter :service()
 CoyoteAdapter -> StandardEngineValve :invoke()
 StandardEngineValve -> AbstractAccessLogValve :invoke()
 AbstractAccessLogValve -> ErrorReportValve :invoke()
 ErrorReportValve -> StandardHostValve :invoke()
 StandardHostValve -> AuthenticatorBase :invoke()
 AuthenticatorBase -> StandardContextValve :invoke()
 StandardContextValve -> StandardWrapperValve :invoke()
 StandardWrapperValve -> ApplicationFilterChain :doFilter()
 ApplicationFilterChain -> ApplicationFilterChain :internalDoFilter()
 ApplicationFilterChain -> HttpServlet :service()
 HttpServlet -> FrameworkServlet :service()
 FrameworkServlet -> HttpServlet :service()
 HttpServlet -> FrameworkServlet :doGet()
 FrameworkServlet -> FrameworkServlet :processRequest()
 FrameworkServlet -> DispatcherServlet :doService()
 DispatcherServlet -> DispatcherServlet :doDispatch()
 DispatcherServlet -> AnnotationMethodHandlerAdapter :handle()
 AnnotationMethodHandlerAdapter -> AnnotationMethodHandlerAdapter :invokeHandlerMethod()
 AnnotationMethodHandlerAdapter -> HandlerMethodInvoker :invokeHandlerMethod()
 HandlerMethodInvoker -> HelloController :printWelcome()
 HelloController -> RequestFacade :getParameter()
 RequestFacade -> Request :getParameter()
 Request -> Request :parseParameters()
@enduml